### ISSUE TITLE
Connect mainnet fails

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/ark-client#18]
Looks like connect mainnet fails.

Line 349 should be replaced with:
}, self);
Line 353 should be replaced with:
function connect2network(n, callback, self){
Line 362 should be replaced with:
if(!body) connect2network(n, callback, self);
Line 365 will then work properly.

Source of information: https://redd.it/79c9ps

**Comment by boldninja** [comment]
@alexbarnsley  can you look this over?

**Comment by alexbarnsley** [comment]
Sure can @boldninja. On it like the bonnet of cars!

**Comment by alexbarnsley** [comment]
This might be a node version issue. @Jarunik - do you know what the symptom of the issue was? I'm able to connect to a node and do network stats without any changes on the master branch:

```
alexj@Alex-Laptop MINGW64 ~/projects/ark-client (master)
$ node index.js
    ___         __      _________            __
   /   |  _____/ /__   / ____/ (_)__  ____  / /_
  / /| | / ___/ //_/  / /   / / / _ \/ __ \/ __/
 / ___ |/ /  / ,<    / /___/ / /  __/ / / / /_
/_/  |_/_/  /_/|_|   \____/_/_/\___/_/ /_/\__/

ark> connect node 92.222.216.118:4001
Connected to network 6e84d08bd299ed97c212c886c98a57e36545c8f5d645ca7eeae63a8bd62d8988 (mainnet)
ark 92.222.216.118:4001> { nethash: '6e84d08bd299ed97c212c886c98a57e36545c8f5d645ca7eeae63a8bd62d8988',
  token: 'ARK',
  symbol: 'Ѧ',
  explorer: 'https://explorer.ark.io',
  version: 23 }
Node height  2413140
ark 92.222.216.118:4001>
```

Versions:

```
alexj@Alex-Laptop MINGW64 ~/projects/ark-client (master)
$ node -v
v8.4.0

alexj@Alex-Laptop MINGW64 ~/projects/ark-client (master)
$ npm -v
5.3.0
```

That being said, was you having the issue personally? If so, can you revert your changes and add the below line at the start of the connect2network method please?:

```
var self = this;
```

I could probably make the above change without any problems to my version, assuming it fixes it. The original poster has removed their Reddit user I think, so the messages are gone.

Thanks!

**Comment by alexbarnsley** [comment]
@Jarunik I've replicated the issue. It's specifically when doing `connect mainnet` which I didn't realise. I'll fix 👍

**Comment by Jarunik** [comment]
Yes it is just connect mainnet which is the problem. :-)

**Comment by alexbarnsley** [comment]
Thanks! 😁 Sorted by changing `self.log` to `vorpal.log` 👌 although I have questioned whether it's needed at all, as looks like debug

**Comment by Jarunik** [comment]
Yes. It is just for connect mainnet.
